### ISSUE TITLE
Failed to activate the codesenderpe1 package

### ISSUE THREAD

**Issue by Hidenari-Kiyomitsu** [kenglwo/atom-package#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [codesenderpe1](https://github.com/kenglwo/atom-package) package 1.2.6

### Stack Trace

Failed to activate the codesenderpe1 package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:1037:7)
    at /packages/codesenderpe1/lib/git-hook.js:37:22)
    at /packages/codesenderpe1/lib/git-hook.js:362:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3196139)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3184123)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3183901
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3181511)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3183761
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3183704)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383037)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382653
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332206)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382603)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382153)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717579
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718064)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
codesenderpe1 1.2.6 
japanese-menu 1.15.0 
monokai 0.24.0 
```

**Comment by Hidenari-Kiyomitsu** [comment]
When other repository opens, then a red indicator rises up.

**Comment by kenglwo** [comment]
Modified the package to allow only one repository(directory) to be opened. 

If multiple directories are opened during the package's activation, an alert window will pop up saying "Multiple directories are opened. Just open one working directory".
